#Docker-compose file to deploy services automatically in the cloud

version: "3.9"

services: 
  nodered:
      container_name: nodered
      image: nodered/node-red:latest
      restart: unless-stopped
      environment: 
        - TZ=Europe/Madrid
      ports:
        - 1880:1880
      volumes:
        - ./volumes/nodered/data:/data
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped 
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Europe/Madrid
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./volumes/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./volumes/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_DB=co2sensor
      - INFLUXDB_USER=openCO2
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin 
      - TZ=Europe/Madrid