#Docker-compose file to deploy services automatically in the cloud

version: "3.3"

services: 
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    environment: 
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped 
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - TZ=Europe/Madrid
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./volumes/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./volumes/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_DB=co2sensor
      - INFLUXDB_USER=openCO2
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD} 
      - TZ=Europe/Madrid
  nodered:
      container_name: nodered
      image: nodered/node-red:latest
      restart: unless-stopped
      user: "0"
      privileged: true
      depends_on:
      - mosquitto
      - influxdb
      environment: 
        - TZ=Europe/Madrid
      ports:
        - 1880:1880
      volumes:
        - ./volumes/nodered/data:/data
